name: PMD Analysis

on:
  push:
    branches:
    - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: '17'

    - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
        version: '6.54.0'
        sourcePath: 'src/main/java'
        rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: pmd-report.sarif

    - name: Parse PMD Report
      run: pmd-cpd-parse -r pmd-report.xml -f plain -d ', ' -e 10 -n 20 > pmd-violations.txt

    - name: Check for PMD violations
      run: |
        if [ -s pmd-violations.txt ]
        then
          echo "PMD violations found:"
          cat pmd-violations.txt
          exit 1
        else
          echo "No PMD violations found"
        fi
