name: PMD Analysis

on:
  push:
    branches:
    - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: '17'

    - name: Install PMD
      run: |
        wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.38.0/pmd-bin-6.38.0.zip
        unzip pmd-bin-6.38.0.zip
        export PATH=$PATH:$PWD/pmd-bin-6.38.0/bin

    - name: Run PMD Analysis
      run: pmd -d src/ -R ruleses/java/ruleset.xml -f xml -r pmd-report.xml

    - name: Upload PMD analysis report
      uses: actions/upload-artifact@v2
      with:
        name: pmd-analysis-report
        path: |
          pmd-report.xml
          pmd-test-report.xml

    - name: Parse PMD Report
      run: pmd-cpd-parse -r pmd-report.xml -f plain -d ', ' -e 10 -n 20 > pmd-violations.txt

    - name: Check for PMD violations
      run: |
        if [ -s pmd-violations.txt ]
        then
          echo "PMD violations found:"
          cat pmd-violations.txt
          exit 1
        else
          echo "No PMD violations found"
        fi
