name: PMD Analysis

on:
  push:
    branches:
    - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: oracle

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: '17'

    - name: Install PMD
      run: |
        wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.38.0/pmd-bin-6.38.0.zip
        unzip pmd-bin-6.38.0.zip
        export PATH=$PATH:$PWD/pmd-bin-6.38.0/bin

    - name: Run PMD Analysis
      run: |
        pmd -d src/ -R rulesets/java/ruleset.xml -f xml -r pmd-report.xml

    - name: Parse PMD Report
      run: pmd-cpd-parse -r pmd-report.xml -f plain -d ', ' -e 10 -n 20 > pmd-violations.txt

    - name: Check for PMD violations
      run: |
        if [ -s pmd-violations.txt ]
        then
          echo "PMD violations found:"
          cat pmd-violations.txt
          exit 1
        else
          echo "No PMD violations found"
        fi

    - name: Use ChatGPT to suggest improvements
      if: always()
      uses: OpenAI/gpt@v1
      id: chatgpt
      with:
        prompt: |
          Please suggest improvements for the following code:
          ```
          $(cat src/Main.java)
          ```
        token: ${{ secrets.OPENAI_API_KEY }}
        temperature: 0.5
        max-tokens: 1024
        n: 1

    - name: Post ChatGPT suggestion as a comment
      if: always()
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'Here is a suggestion from ChatGPT: ' + '${{ steps.chatgpt.outputs.result }}'
          })
        token: ${{ secrets.GITHUB_TOKEN }}
