name: PMD Analysis

on:
  push:
    branches:
    - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: '17'

    - name: PMD Code Analyzer Action
      uses: billyan2018/setup-pmd@PMDAnalyzer1.0
      run: |
        pmd -d src/ -R rulesets/java/ruleset.xml -f xml -r pmd-report.xml

    - name: Parse PMD Report
      run: pmd-cpd-parse -r pmd-report.xml -f plain -d ', ' -e 10 -n 20 > pmd-violations.txt

    - name: Check for PMD violations
      run: |
        if [ -s pmd-violations.txt ]
        then
          echo "PMD violations found:"
          cat pmd-violations.txt
          exit 1
        else
          echo "No PMD violations found"
        fi
